const KEY="academia_assignments_v2";
const defaultAssignments=[
{id:"a1",subject:"DAA",title:"Dynamic Programming",description:"Solve and document dynamic programming problems with complexity analysis.",teacher:"Dr. Priya",priority:"high",dueDate:"2026-10-06",dueTime:"23:59",progress:90,status:"active",difficulty:"Hard",estimatedMinutes:90,tags:["dp","practice"],type:"Assignment",attachment:"DP-Problems.pdf",createdAt:"2026-10-01"},
{id:"a2",subject:"Web Technology",title:"Responsive Dashboard",description:"Build a responsive academic dashboard UI with reusable components.",teacher:"Ms. Anitha",priority:"high",dueDate:"2026-10-12",dueTime:"23:59",progress:72,status:"active",difficulty:"Medium",estimatedMinutes:150,tags:["html","css","project"],type:"Project",attachment:"requirements.pdf",createdAt:"2026-10-02"},
{id:"a3",subject:"Mathematics",title:"Matrix Factorisation",description:"Complete the factorisation method practice set and submit workings.",teacher:"Dr. Kumar",priority:"medium",dueDate:"2026-10-13",dueTime:"17:00",progress:55,status:"active",difficulty:"Medium",estimatedMinutes:75,tags:["matrices","practice"],type:"Assignment",attachment:"",createdAt:"2026-10-02"},
{id:"a4",subject:"Data Engineering",title:"Database Mini Project",description:"Prepare schema, SQL queries and screenshots for the mini project.",teacher:"Mr. Ravi",priority:"low",dueDate:"2026-10-16",dueTime:"22:00",progress:35,status:"active",difficulty:"Hard",estimatedMinutes:180,tags:["sql","database","project"],type:"Project",attachment:"schema.sql",createdAt:"2026-10-03"},
{id:"a5",subject:"Operating Systems",title:"Process Scheduling Lab",description:"Implement and compare FCFS, SJF and Round Robin scheduling.",teacher:"Ms. Meena",priority:"critical",dueDate:"2026-10-07",dueTime:"18:00",progress:20,status:"active",difficulty:"Hard",estimatedMinutes:120,tags:["os","lab"],type:"Lab",attachment:"lab-sheet.pdf",createdAt:"2026-10-03"},
{id:"a6",subject:"Computer Networks",title:"Midterm Revision",description:"Revise routing, transport layer and subnetting before the exam.",teacher:"Dr. Arjun",priority:"high",dueDate:"2026-10-09",dueTime:"09:00",progress:40,status:"active",difficulty:"Medium",estimatedMinutes:120,tags:["revision","exam"],type:"Exam",attachment:"syllabus.pdf",createdAt:"2026-10-03"},
{id:"a7",subject:"AI Fundamentals",title:"Search Algorithms Quiz",description:"Practice uninformed and informed search algorithm questions.",teacher:"Dr. Nisha",priority:"medium",dueDate:"2026-10-03",dueTime:"12:00",progress:100,status:"completed",difficulty:"Easy",estimatedMinutes:45,tags:["ai","quiz"],type:"Assignment",attachment:"",createdAt:"2026-09-29",completedAt:"2026-10-02"}
];
let assignments=load();
let activeFilter="all", currentView="dashboard", calendarDate=new Date(2026,9,5), calendarMode="month";
let timer={seconds:1500,remaining:1500,running:false,interval:null,mode:"focus",taskId:null};

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return Array.isArray(x)?x:structuredClone(defaultAssignments)}catch{return structuredClone(defaultAssignments)}}
function save(){localStorage.setItem(KEY,JSON.stringify(assignments))}
function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function dateOnly(a){return new Date(a+"T12:00:00")}
function today(){return new Date()}
function startToday(){const d=today();d.setHours(0,0,0,0);return d}
function daysBetween(a,b){return Math.round((dateOnly(a)-dateOnly(b))/86400000)}
function isOverdue(a){return a.progress<100 && dateOnly(a.dueDate)<startToday()}
function priorityWeight(p){return {critical:4,high:3,medium:2,low:1}[p]||0}
function fmtDate(a){return dateOnly(a).toLocaleDateString(undefined,{month:"short",day:"numeric"})}
function toast(msg,type=""){const el=document.createElement("div");el.className="toast "+type;el.textContent=msg;$("#toastStack").append(el);setTimeout(()=>el.remove(),3000)}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function stats(){const active=assignments.filter(a=>a.progress<100), overdue=active.filter(isOverdue), soon=active.filter(a=>{const d=daysBetween(a.dueDate,startToday());return d>=0&&d<=7}), done=assignments.filter(a=>a.progress>=100);return {active,overdue,soon,done,pct:assignments.length?Math.round(done.length/assignments.length*100):0}}
function greeting(){const h=new Date().getHours();return h<12?"GOOD MORNING":h<18?"GOOD AFTERNOON":"GOOD EVENING"}
$("#greeting").textContent=greeting();

function showView(v){
 currentView=v; $$(".view").forEach(x=>x.classList.remove("active")); $("#"+v+"View").classList.add("active");
 $$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===v));
 $("#viewTitle").textContent={dashboard:"Academic Command Center",assignments:"Assignments",calendar:"Academic Calendar",analytics:"Progress Analytics",focus:"Focus Mode"}[v];
 if(v==="calendar")renderCalendar(); if(v==="analytics")renderAnalytics(); if(v==="focus")renderFocus();
 $("#sidebar").classList.remove("open"); window.scrollTo({top:0,behavior:"smooth"});
}
$$(".nav-item").forEach(b=>b.onclick=()=>showView(b.dataset.view));
$$("[data-view]").forEach(b=>{if(!b.classList.contains("nav-item"))b.onclick=()=>showView(b.dataset.view)});
$("#openSidebar").onclick=()=>$("#sidebar").classList.add("open");$("#closeSidebar").onclick=()=>$("#sidebar").classList.remove("open");

function assignmentRow(a){
 return `<div class="assignment-row"><div class="assignment-main"><i class="subject-dot"></i><div><b>${esc(a.title)}</b><p>${esc(a.subject)} · ${fmtDate(a.dueDate)} · ${a.dueTime}</p><div class="progress-line"><i style="width:${a.progress}%"></i></div></div></div><span class="priority ${a.priority}">${a.priority}</span></div>`
}
function renderDashboard(){
 const s=stats();$("#statSoon").textContent=String(s.soon.length).padStart(2,"0");$("#statOverdue").textContent=String(s.overdue.length).padStart(2,"0");$("#statActive").textContent=String(s.active.length).padStart(2,"0");$("#statProgress").textContent=s.pct+"%";$("#heroProgress").textContent=s.pct+"%";$("#navCount").textContent=assignments.length;
 const queue=[...s.active].sort((a,b)=>priorityWeight(b.priority)-priorityWeight(a.priority)||dateOnly(a.dueDate)-dateOnly(b.dueDate)).slice(0,5);
 $("#dashboardAssignments").innerHTML=queue.length?queue.map(assignmentRow).join(`<div></div>`):`<div class="empty">No active assignments 🎉</div>`;
 const focus=[...s.active].sort((a,b)=>dateOnly(a.dueDate)-dateOnly(b.dueDate)).slice(0,2);
 $("#todayFocus").innerHTML=focus.length?focus.map(a=>`<div class="quick-item"><i class="quick-dot"></i><div><b>${esc(a.title)}</b><span>${esc(a.subject)} · ${a.progress}% complete · due ${fmtDate(a.dueDate)}</span></div></div>`).join(""):`<div class="quick-item"><div><b>All caught up.</b><span>Enjoy your free study time.</span></div></div>`;
 const radar=[...s.active].sort((a,b)=>dateOnly(a.dueDate)-dateOnly(b.dueDate)).slice(0,5);$("#radar").innerHTML=radar.map(a=>`<div class="radar-item"><time>${isOverdue(a)?"OVERDUE":fmtDate(a.dueDate)+" · "+a.dueTime}</time><b>${esc(a.title)}</b></div>`).join("")||`<div class="empty">No deadlines.</div>`;
 renderWorkload(); $("#miniAnalytics").innerHTML=`<div class="mini-stat"><span>Completed</span><b>${s.done.length}</b></div><div class="mini-stat"><span>Pending</span><b>${s.active.length}</b></div><div class="mini-stat"><span>Overdue</span><b>${s.overdue.length}</b></div><div class="mini-stat"><span>Average progress</span><b>${assignments.length?Math.round(assignments.reduce((n,a)=>n+a.progress,0)/assignments.length):0}%</b></div>`;
}
function workloadData(){const out=Array(7).fill(0), base=startToday();assignments.filter(a=>a.progress<100).forEach(a=>{const d=daysBetween(a.dueDate,base);if(d>=0&&d<7)out[d]+=Number(a.estimatedMinutes)||0});return out}
function renderWorkload(target="#workloadBars"){const vals=workloadData(),max=Math.max(...vals,60), names=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"], start=startToday().getDay()||7;$(target).innerHTML=names.map((n,i)=>{const idx=(start-1+i)%7,v=vals[idx];return `<div class="bar-col"><div class="bar" style="height:${Math.max(4,v/max*100)}%"></div><span>${n}</span><small>${v}m</small></div>`}).join("");const busy=vals.indexOf(Math.max(...vals));$("#busyWarning").textContent=Math.max(...vals)>240?`⚠ Heavy load: ${names[busy]}`:"Balanced week";}
function renderAssignments(){
 let arr=[...assignments];const q=$("#searchInput").value.trim().toLowerCase();
 if(q)arr=arr.filter(a=>{const text=[a.subject,a.title,a.description,a.teacher,a.type,...a.tags].join(" ").toLowerCase();return text.includes(q)|| (q.includes("due tomorrow")&&daysBetween(a.dueDate,startToday())===1)||(q.includes("due today")&&daysBetween(a.dueDate,startToday())===0)||(q.includes("overdue")&&isOverdue(a))||(q.includes("high priority")&&["high","critical"].includes(a.priority))});
 arr=arr.filter(a=>{if(activeFilter==="all")return true;if(activeFilter==="today")return daysBetween(a.dueDate,startToday())===0&&!isOverdue(a);if(activeFilter==="week")return daysBetween(a.dueDate,startToday())>=0&&daysBetween(a.dueDate,startToday())<=7&&!isOverdue(a);if(activeFilter==="overdue")return isOverdue(a);if(activeFilter==="completed")return a.progress>=100;if(activeFilter==="high")return ["high","critical"].includes(a.priority);return a.type.toLowerCase()===activeFilter.slice(0,-1)||a.type.toLowerCase()===activeFilter});
 const sort=$("#sortSelect").value;arr.sort((a,b)=>sort==="priority"?priorityWeight(b.priority)-priorityWeight(a.priority):sort==="progress"?b.progress-a.progress:sort==="subject"?a.subject.localeCompare(b.subject):dateOnly(a.dueDate)-dateOnly(b.dueDate));
 $("#assignmentBoard").innerHTML=arr.length?arr.map(card).join(""):`<div class="panel empty" style="grid-column:1/-1">No assignments match this view. Try another filter or add a new assignment.</div>`;
 $$(".open-detail").forEach(b=>b.onclick=()=>openDetail(b.dataset.id));
}
function card(a){return `<article class="assignment-card"><div class="card-top"><div><span class="pill ${a.priority==="critical"||a.priority==="high"?"purple":"cyan"}">${esc(a.subject)}</span><h3>${esc(a.title)}</h3></div><span class="priority ${a.priority}">${a.priority}</span></div><p class="desc">${esc(a.description||"No description added.")}</p><div class="meta"><span class="tag">${esc(a.type)}</span><span class="tag">${esc(a.difficulty)}</span><span class="tag">${isOverdue(a)?"Overdue":"Due "+fmtDate(a.dueDate)}</span><span class="tag">${a.estimatedMinutes} min</span></div><div class="progress-line"><i style="width:${a.progress}%"></i></div><div class="card-bottom"><small>${a.progress}% complete</small><button class="ghost-btn open-detail" data-id="${a.id}">Details →</button></div></article>`}

function openDetail(id){const a=assignments.find(x=>x.id===id);if(!a)return;$("#drawerContent").innerHTML=`<div class="detail-hero"><span class="pill purple">${esc(a.subject)}</span><h2>${esc(a.title)}</h2><div class="detail-sub">${esc(a.teacher||"No teacher")} · ${esc(a.type)}</div><div class="detail-progress"><i style="width:${a.progress}%"></i></div><p style="color:#8a94ab;line-height:1.7;font-size:12px">${esc(a.description||"No description.")}</p><div class="detail-grid"><div class="detail-box"><small>DEADLINE</small><b>${fmtDate(a.dueDate)} · ${a.dueTime}</b></div><div class="detail-box"><small>PRIORITY</small><b>${a.priority.toUpperCase()}</b></div><div class="detail-box"><small>DIFFICULTY</small><b>${a.difficulty}</b></div><div class="detail-box"><small>EST. TIME</small><b>${a.estimatedMinutes} min</b></div><div class="detail-box"><small>PROGRESS</small><b>${a.progress}%</b></div><div class="detail-box"><small>ATTACHMENT</small><b>${esc(a.attachment||"None")}</b></div></div><div class="meta">${a.tags.map(t=>`<span class="tag">#${esc(t)}</span>`).join("")}</div><div class="detail-actions"><button class="primary-btn" onclick="startFocusFor('${a.id}')">Focus on task</button><button class="ghost-btn" onclick="editAssignment('${a.id}')">Edit</button><button class="ghost-btn" onclick="completeAssignment('${a.id}')">${a.progress>=100?"Reopen":"Mark complete"}</button><button class="ghost-btn" onclick="deleteAssignment('${a.id}')">Delete</button></div></div>`;$("#drawer").classList.add("open");$("#drawerBackdrop").classList.add("show")}
function closeDrawer(){$("#detailDrawer").classList.remove("open");$("#drawerBackdrop").classList.remove("show")}$("#closeDrawer").onclick=closeDrawer;$("#drawerBackdrop").onclick=closeDrawer;

function openForm(a=null){$("#assignmentForm").reset();$("#editId").value=a?.id||"";$("#modalTitle").textContent=a?"Edit assignment":"Add assignment";if(a){for(const [id,val] of [["fSubject",a.subject],["fTitle",a.title],["fDescription",a.description],["fTeacher",a.teacher],["fType",a.type],["fPriority",a.priority],["fDifficulty",a.difficulty],["fDueDate",a.dueDate],["fDueTime",a.dueTime],["fProgress",a.progress],["fMinutes",a.estimatedMinutes],["fTags",a.tags.join(", ")],["fAttachment",a.attachment]])$( "#"+id).value=val??""}else{$("#fDueDate").value=new Date().toISOString().slice(0,10)}$("#modalBackdrop").classList.add("show")}
function closeForm(){$("#modalBackdrop").classList.remove("show")}$("#addBtn").onclick=()=>openForm();$("#closeModal").onclick=closeForm;$("#cancelForm").onclick=closeForm;$("#modalBackdrop").onclick=e=>{if(e.target.id==="modalBackdrop")closeForm()}
$("#assignmentForm").onsubmit=e=>{e.preventDefault();const data={subject:$("#fSubject").value.trim(),title:$("#fTitle").value.trim(),description:$("#fDescription").value.trim(),teacher:$("#fTeacher").value.trim(),type:$("#fType").value,priority:$("#fPriority").value,difficulty:$("#fDifficulty").value,dueDate:$("#fDueDate").value,dueTime:$("#fDueTime").value||"23:59",progress:Math.max(0,Math.min(100,Number($("#fProgress").value)||0)),estimatedMinutes:Math.max(5,Number($("#fMinutes").value)||60),tags:$("#fTags").value.split(",").map(x=>x.trim()).filter(Boolean),attachment:$("#fAttachment").value.trim()};const eid=$("#editId").value;if(eid){const a=assignments.find(x=>x.id===eid);Object.assign(a,data);if(a.progress>=100)a.completedAt=a.completedAt||new Date().toISOString()}else assignments.push({...data,id:id(),status:data.progress>=100?"completed":"active",createdAt:new Date().toISOString()});save();closeForm();renderAll();toast(eid?"Assignment updated":"Assignment added","good")};
function editAssignment(id){closeDrawer();const a=assignments.find(x=>x.id===id);if(a)openForm(a)}
function deleteAssignment(id){const a=assignments.find(x=>x.id===id);if(a&&confirm(`Delete "${a.title}"?`)){assignments=assignments.filter(x=>x.id!==id);save();closeDrawer();renderAll();toast("Assignment deleted")}}
function completeAssignment(id){const a=assignments.find(x=>x.id===id);if(!a)return;a.progress=a.progress>=100?0:100;a.status=a.progress>=100?"completed":"active";a.completedAt=a.progress>=100?new Date().toISOString():null;save();closeDrawer();renderAll();toast(a.progress>=100?"Assignment completed 🎉":"Assignment reopened","good")}

function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth();$("#calendarTitle").textContent=calendarDate.toLocaleDateString(undefined,{month:"long",year:"numeric"});if(calendarMode==="month")renderMonth(y,m);else if(calendarMode==="week")renderWeek();else if(calendarMode==="day")renderDay();else renderSemester()}
function eventHtml(a){return `<div class="cal-event" onclick="openDetail('${a.id}')">${esc(a.title)}</div>`}
function renderMonth(y,m){const first=new Date(y,m,1),last=new Date(y,m+1,0),offset=(first.getDay()+6)%7,total=Math.ceil((offset+last.getDate())/7)*7;let h='<div class="month-grid">'+["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(x=>`<div class="weekday">${x}</div>`).join("");for(let i=0;i<total;i++){const d=i-offset+1,valid=d>0&&d<=last.getDate(),ds=valid?`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`:"",ev=assignments.filter(a=>a.dueDate===ds);h+=`<div class="day-cell ${ds===new Date().toISOString().slice(0,10)?"today":""}">${valid?`<div class="day-num">${d}</div>${ev.slice(0,3).map(eventHtml).join("")}${ev.length>3?`<div class="cal-event">+${ev.length-3} more</div>`:""}`:""}</div>`}$("#calendarPanel").innerHTML=h+"</div>"}
function renderWeek(){const base=new Date(calendarDate),day=(base.getDay()+6)%7;base.setDate(base.getDate()-day);let h='<div class="week-view"><div class="week-row"><div class="week-head">TIME</div>';for(let i=0;i<7;i++){const d=new Date(base);d.setDate(base.getDate()+i);h+=`<div class="week-head">${d.toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"})}</div>`}h+="";for(let r=8;r<=20;r+=2){h+=`<div>${String(r).padStart(2,"0")}:00</div>`;for(let i=0;i<7;i++){const d=new Date(base);d.setDate(base.getDate()+i);const ds=d.toISOString().slice(0,10);h+=`<div>${assignments.filter(a=>a.dueDate===ds&&Number(a.dueTime.slice(0,2))>=r&&Number(a.dueTime.slice(0,2))<r+2).map(eventHtml).join("")}</div>`} }$("#calendarPanel").innerHTML=h+"</div></div>"}
function renderDay(){const ds=calendarDate.toISOString().slice(0,10),ev=assignments.filter(a=>a.dueDate===ds);$("#calendarPanel").innerHTML=`<div class="day-view"><span class="eyebrow">SELECTED DAY</span><div class="day-large">${calendarDate.toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"})}</div>${ev.length?ev.map(a=>`<div class="assignment-row" onclick="openDetail('${a.id}')" style="cursor:pointer">${assignmentRow(a)}</div>`).join(""):"<p style='color:#7d879e'>No assignments due on this day.</p>"}</div>`}
function renderSemester(){const arr=[...assignments].sort((a,b)=>dateOnly(a.dueDate)-dateOnly(b.dueDate));$("#calendarPanel").innerHTML=`<div class="semester-view"><p style="color:#778198;font-size:12px">Semester view groups every assignment in deadline order.</p>${arr.map(a=>`<div class="semester-item"><div><b>${esc(a.title)}</b><div style="color:#737d94;font-size:10px;margin-top:4px">${esc(a.subject)} · ${esc(a.type)}</div></div><div style="text-align:right"><b>${fmtDate(a.dueDate)}</b><div style="color:#737d94;font-size:10px">${a.progress}% complete</div></div></div>`).join("")}</div>`}
$("#prevMonth").onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()};$("#nextMonth").onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()};$("#todayCalendar").onclick=()=>{calendarDate=new Date();renderCalendar()};$$(".cal-mode").forEach(b=>b.onclick=()=>{$$(".cal-mode").forEach(x=>x.classList.remove("active"));b.classList.add("active");calendarMode=b.dataset.calMode;renderCalendar()});

function renderAnalytics(){const s=stats(),p=s.pct;$("#analyticsPct").textContent=p+"%";$("#analyticsRing").style.background=`conic-gradient(#8b5cf6 ${p*3.6}deg,#242a3d 0deg)`;$("#aCompleted").textContent=s.done.length;$("#aPending").textContent=s.active.length;$("#aOverdue").textContent=s.overdue.length;$("#aAvg").textContent=assignments.length?Math.round(assignments.reduce((n,a)=>n+a.estimatedMinutes,0)/assignments.length)+"m":"—";$("#analyticsHeadline").textContent=p>=80?"Excellent momentum":p>=50?"Building momentum":"Start with one task";$("#analyticsText").textContent=s.overdue.length?`You have ${s.overdue.length} overdue item${s.overdue.length>1?"s":""}. Clear the oldest deadline first.`:"Your deadline radar is under control. Keep the streak going.";const subjects={};assignments.forEach(a=>{subjects[a.subject]??={total:0,done:0};subjects[a.subject].total++;if(a.progress>=100)subjects[a.subject].done++});$("#subjectChart").innerHTML=Object.entries(subjects).map(([n,v])=>{const pct=Math.round(v.done/v.total*100);return `<div class="subject-row"><div class="subject-label"><span>${esc(n)}</span><b>${pct}%</b></div><div class="subject-bar"><i style="width:${pct}%"></i></div></div>`}).join("");renderWorkload("#analyticsBars")}
function renderFocus(){const active=assignments.filter(a=>a.progress<100);$("#focusSelect").innerHTML=active.length?active.map(a=>`<option value="${a.id}">${esc(a.subject)} — ${esc(a.title)}</option>`).join(""):`<option>No pending tasks</option>`;if(timer.taskId&&!assignments.some(a=>a.id===timer.taskId))timer.taskId=null;if(!timer.taskId&&active[0])timer.taskId=active[0].id;updateTimerUI()}
function startFocusFor(id){closeDrawer();showView("focus");timer.taskId=id;const a=assignments.find(x=>x.id===id);timer.seconds=(a?.estimatedMinutes||25)*60;timer.remaining=timer.seconds;timer.running=false;$("#focusSelect").value=id;updateTimerUI();startTimer()}
$("#focusSelect").onchange=e=>{timer.taskId=e.target.value;const a=assignments.find(x=>x.id===timer.taskId);timer.seconds=(a?.estimatedMinutes||25)*60;timer.remaining=timer.seconds;timer.running=false;updateTimerUI()}
function updateTimerUI(){const mins=Math.floor(timer.remaining/60),secs=timer.remaining%60;$("#timerDisplay").textContent=`${String(mins).padStart(2,"0")}:${String(secs).padStart(2,"0")}`;$("#timerLabel").textContent=timer.mode==="break"?"BREAK":timer.running?"FOCUSING":"READY";const pct=timer.seconds?1-timer.remaining/timer.seconds:0;$("#timerRing").style.background=`conic-gradient(#06b6d4 ${pct*360}deg,#8b5cf6 ${pct*360+70}deg,#20263a ${pct*360+70}deg)`;$("#timerPause").textContent=timer.running?"Pause":"Resume"}
function startTimer(){if(timer.running)return;timer.running=true;clearInterval(timer.interval);timer.interval=setInterval(()=>{if(timer.remaining>0){timer.remaining--;updateTimerUI()}else{clearInterval(timer.interval);timer.running=false;toast(timer.mode==="focus"?"Focus session complete!":"Break complete.","good");if(timer.mode==="focus")finishFocus(false);updateTimerUI()}},1000);updateTimerUI()}
$("#focusStart").onclick=()=>startTimer();$("#timerPause").onclick=()=>{timer.running? (clearInterval(timer.interval),timer.running=false):(startTimer());updateTimerUI()};$("#focusReset").onclick=()=>{clearInterval(timer.interval);timer.running=false;timer.mode="focus";const a=assignments.find(x=>x.id===timer.taskId);timer.seconds=(a?.estimatedMinutes||25)*60;timer.remaining=timer.seconds;updateTimerUI()};$("#timerBreak").onclick=()=>{clearInterval(timer.interval);timer.mode="break";timer.seconds=300;timer.remaining=300;timer.running=false;updateTimerUI();startTimer()};$("#timerFinish").onclick=()=>finishFocus(true);
function finishFocus(manual){const a=assignments.find(x=>x.id===timer.taskId);if(a&&timer.mode==="focus"){a.progress=100;a.status="completed";a.completedAt=new Date().toISOString();save();renderAll();toast(manual?"Task marked complete 🎉":"Task session finished — marked complete","good")}clearInterval(timer.interval);timer.running=false;timer.mode="focus";renderFocus()}

function notifications(){const s=stats(),items=[];s.overdue.slice(0,3).forEach(a=>items.push(`<div class="notification-item"><b>Overdue: ${esc(a.title)}</b><p>${esc(a.subject)} was due ${fmtDate(a.dueDate)}.</p></div>`));s.soon.slice(0,4).forEach(a=>items.push(`<div class="notification-item"><b>Due soon: ${esc(a.title)}</b><p>${fmtDate(a.dueDate)} · ${a.dueTime} · ${a.progress}% complete.</p></div>`));if(!items.length)items.push(`<div class="notification-item"><b>All clear</b><p>No urgent academic alerts right now.</p></div>`);$("#notificationList").innerHTML=items.join("");$("#notificationDot").classList.toggle("on",s.overdue.length>0||s.soon.length>0)}
$("#notifyBtn").onclick=()=>{$("#notificationPanel").classList.toggle("show");notifications()};$("#closeNotifications").onclick=()=>$("#notificationPanel").classList.remove("show");

function openCommand(){renderCommands("");$("#commandBackdrop").classList.add("show");$("#commandInput").focus()}function renderCommands(q){const base=[{name:"Add new assignment",action:"add"},{name:"Open dashboard",action:"dashboard"},{name:"Open calendar",action:"calendar"},{name:"Open analytics",action:"analytics"},{name:"Open focus mode",action:"focus"},{name:"Show overdue",action:"overdue"}];const tasks=assignments.filter(a=>[a.title,a.subject,...a.tags].join(" ").toLowerCase().includes(q.toLowerCase())).slice(0,5).map(a=>({name:`Open ${a.title}`,action:"task:"+a.id}));const arr=[...base,...tasks];$("#commandResults").innerHTML=arr.map(x=>`<div class="command-result" data-action="${x.action}"><span>${esc(x.name)}</span><small>↵</small></div>`).join("");$$(".command-result").forEach(x=>x.onclick=()=>commandAction(x.dataset.action))}
function commandAction(a){$("#commandBackdrop").classList.remove("show");if(a==="add")openForm();else if(["dashboard","calendar","analytics","focus"].includes(a))showView(a);else if(a==="overdue"){showView("assignments");activeFilter="overdue";$$(".filter").forEach(x=>x.classList.toggle("active",x.dataset.filter==="overdue"));renderAssignments()}else if(a.startsWith("task:"))openDetail(a.slice(5))}
$("#openCommand").onclick=openCommand;document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openCommand()}if(e.key==="Escape"){closeForm();$("#commandBackdrop").classList.remove("show");$("#notificationPanel").classList.remove("show")}});$("#commandBackdrop").onclick=e=>{if(e.target.id==="commandBackdrop")$("#commandBackdrop").classList.remove("show")};$("#commandInput").oninput=e=>renderCommands(e.target.value);

$("#searchInput").oninput=renderAssignments;$("#sortSelect").onchange=renderAssignments;$$(".filter").forEach(b=>b.onclick=()=>{activeFilter=b.dataset.filter;$$(".filter").forEach(x=>x.classList.toggle("active",x===b));renderAssignments()});
$("#startNext").onclick=()=>{const a=[...stats().active].sort((x,y)=>dateOnly(x.dueDate)-dateOnly(y.dueDate))[0];if(a)startFocusFor(a.id);else toast("No pending tasks.","good")};

function requestBrowserNotifications(){if("Notification"in window&&Notification.permission==="default")Notification.requestPermission().then(()=>toast("Notification permission updated."))}
document.addEventListener("visibilitychange",()=>{if(!document.hidden)notifications()});
function renderAll(){renderDashboard();renderAssignments();renderAnalytics();renderFocus();notifications()}
renderAll();
