const careers={
 ai:{name:'AI Engineer',icon:'🤖',score:92,growth:'Very High',difficulty:'High',desc:'Build intelligent systems, copilots and machine-learning products.',glow:'#8b7cff'},
 web:{name:'Full Stack Developer',icon:'💻',score:84,growth:'High',difficulty:'Medium',desc:'Design and build modern web applications from interface to backend.',glow:'#55e8ff'},
 design:{name:'Product Designer',icon:'🎨',score:71,growth:'Growing',difficulty:'Medium',desc:'Shape digital products through research, interaction and visual systems.',glow:'#ff67c8'},
 data:{name:'Data Scientist',icon:'📊',score:86,growth:'Very High',difficulty:'High',desc:'Turn data into models, insights and decisions that matter.',glow:'#6cf2b1'},
 cyber:{name:'Cybersecurity Engineer',icon:'🛡️',score:79,growth:'High',difficulty:'High',desc:'Protect systems, networks and people in an increasingly digital world.',glow:'#ffd166'}
};
const skills=[['Python',82,'🐍'],['JavaScript',74,'⚡'],['UI / UX',68,'🎨'],['Data & SQL',59,'📊'],['Machine Learning',41,'🧠'],['Communication',76,'💬']];
const timeline=[['2026','Discover','Map your interests and strongest signals.','done'],['2027','Core skills','Build programming and problem-solving foundations.','done'],['2028','Projects','Create 3–5 meaningful portfolio projects.','current'],['2029','Experience','Internship, open source or real client work.','future'],['2030','Launch','Enter your first target career universe.','future']];
const scenarioData=[['python','🐍','Learn Python','Build a strong programming foundation.',true,8],['projects','🧪','Build 5 projects','Turn skills into evidence through projects.',true,7],['internship','🚀','Take an internship','Add real-world experience to your path.',false,9],['math','∑','Improve mathematics','Strengthen analytical thinking for technical careers.',true,5],['communication','💬','Practice communication','Improve collaboration and interview readiness.',false,4],['ai','🧠','Study machine learning','Explore models, data and intelligent systems.',true,11]];
let state={readiness:78,selectedCareer:'ai',scenario:{},experiments:JSON.parse(localStorage.getItem('eduMultiverseExperiments')||'[]'),sound:true};
scenarioData.forEach(x=>state.scenario[x[0]]=x[4]);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function toast(title,text){$('#toastTitle').textContent=title;$('#toastText').textContent=text;$('#toast').classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>$('#toast').classList.remove('show'),3000);}
function renderCareerCards(target,limit=99){const el=$(target);el.innerHTML=Object.entries(careers).slice(0,limit).map(([key,c])=>`<article class="career-card" style="--card-glow:${c.glow}" data-career-card="${key}"><div class="career-top"><div class="career-icon">${c.icon}</div><span class="match">${c.score}% MATCH</span></div><h3>${c.name}</h3><p>${c.desc}</p><div class="score-bar"><i style="width:${c.score}%"></i></div><div class="card-foot"><span>Growth <b>${c.growth}</b></span><span>Difficulty <b>${c.difficulty}</b></span></div></article>`).join('');
 $$('#'+el.id+' [data-career-card], .career-card').forEach(card=>{card.addEventListener('click',()=>openCareer(card.dataset.careerCard));});}
function openCareer(key){const c=careers[key];state.selectedCareer=key;const reasons={ai:['Strong programming interest','Analytical problem solving','High technical curiosity'],web:['Comfort with building interfaces','Strong practical learning','Interest in product building'],design:['Visual thinking','User empathy','Creative problem solving'],data:['Analytical thinking','Interest in patterns','Comfort with numbers'],cyber:['Problem solving','Security curiosity','Systems thinking']}[key];$('#modalContent').innerHTML=`<span class="eyebrow">${c.icon} CAREER UNIVERSE</span><h2>${c.name}</h2><p>${c.desc} Explore this as a possibility, then compare it with other paths.</p><div class="modal-stats"><div class="modal-stat"><b>${c.score}%</b><span>Compatibility</span></div><div class="modal-stat"><b>${c.growth}</b><span>Growth signal</span></div><div class="modal-stat"><b>${c.difficulty}</b><span>Challenge</span></div></div><h3>Why this universe?</h3><p>✓ ${reasons.join('<br>✓ ')}</p><button class="primary-btn" id="chooseCareer">Enter ${c.name} universe →</button>`;$('#modal').classList.add('open');$('#chooseCareer').onclick=()=>{state.selectedCareer=key;showView('lab');$('#modal').classList.remove('open');toast('Universe selected',`${c.name} is now your active simulation.`);};}
function renderTree(){ $$('.tree-node').forEach(n=>n.addEventListener('click',()=>{ $$('.tree-node').forEach(x=>x.classList.remove('selected'));n.classList.add('selected');const key=n.dataset.branch,c=careers[key];$('#treeDetail').innerHTML=`<b>${c.name}</b> opens a path with <strong>${c.score}% compatibility</strong>. Next: build ${key==='design'?'a portfolio':key==='web'?'web projects':'technical projects'} → gain experience → reassess your future.`; if(state.sound)beep();})); }
function renderSkills(){const galaxy=$('#skillGalaxy');skills.forEach((s,i)=>{const angle=(i/skills.length)*Math.PI*2;const radius=85+(i%3)*52;const x=Math.cos(angle)*radius;const y=Math.sin(angle)*radius;const d=document.createElement('div');d.className='skill-dot';d.style.left=`calc(50% + ${x}px - 26px)`;d.style.top=`calc(50% + ${y}px - 26px)`;d.innerHTML=`${s[2]}<strong>${s[1]}%</strong>`;d.title=s[0];galaxy.appendChild(d);});$('#skillRows').innerHTML=skills.map(s=>`<div class="skill-row"><div class="skill-row-top"><span>${s[2]} ${s[0]}</span><b>${s[1]}%</b></div><div class="skill-progress"><i style="width:${s[1]}%"></i></div></div>`).join('');$('#gapGrid').innerHTML=[['Machine Learning','Current level 41%. Unlocks AI and data paths.','41%'],['Data & SQL','Current level 59%. Useful across AI, data and analytics.','59%'],['Project Experience','Your biggest evidence gap. Build 2 more projects.','48%']].map(g=>`<div class="gap-card"><h4>${g[0]}</h4><p>${g[1]}</p><span class="gap-level">LEVEL ${g[2]}</span></div>`).join('');}
function renderTimeline(){ $('#timelineTrack').innerHTML=timeline.map(t=>`<div class="timeline-node ${t[3]}"><div class="dot"></div><small>${t[0]}</small><h4>${t[1]}</h4><p>${t[2]}</p></div>`).join('');$('#futureCards').innerHTML=[['92%','AI Engineer','Strongest current fit. Focus on Python, ML and projects.'],['84%','Full Stack Developer','A practical alternative with a broad product-building route.'],['71%','Product Designer','A creative universe where user experience becomes your core skill.']].map(x=>`<article class="future-card"><span>PROJECTED FIT</span><div class="big">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('');}
function renderScenarios(){ $('#scenarioOptions').innerHTML=scenarioData.map(x=>`<div class="scenario-option"><div class="scenario-info"><div class="scenario-icon">${x[1]}</div><div><b>${x[2]}</b><small>${x[3]}</small></div></div><button class="switch ${state.scenario[x[0]]?'on':''}" data-scenario="${x[0]}" aria-label="Toggle ${x[2]}"><i></i></button></div>`).join('');$$('.switch').forEach(b=>b.onclick=()=>{const k=b.dataset.scenario;state.scenario[k]=!state.scenario[k];b.classList.toggle('on',state.scenario[k]);updateSimulation(false);if(state.sound)beep();});updateSimulation(false);}
function updateSimulation(show=true){let score=careers[state.selectedCareer].score-20;let impacts=[];scenarioData.forEach(x=>{if(state.scenario[x[0]]){score+=x[5];impacts.push([x[2],`+${x[5]}%`]);}});score=Math.max(40,Math.min(99,score));const delta=score-careers[state.selectedCareer].score;$('#labScore').textContent=score+'%';$('#labCareer').textContent=careers[state.selectedCareer].name;$('#resultDelta').textContent=`${delta>=0?'+':''}${delta}% from baseline path`;$('#impactList').innerHTML=(impacts.length?impacts:[['No additional variables','+0%']]).map(i=>`<div class="impact"><span>${i[0]}</span><b>${i[1]}</b></div>`).join('');if(show){state.readiness=Math.min(99,Math.max(50,Math.round((state.readiness+score)/2)));$('#readinessScore').textContent=state.readiness;$('#heroReadiness').textContent=state.readiness+'%';$('#scoreRing').style.background=`conic-gradient(var(--accent) 0 ${state.readiness}%,rgba(255,255,255,.06) ${state.readiness}%)`;toast('Future simulated',`${careers[state.selectedCareer].name} now projects at ${score}% fit.`);}}
function saveScenario(){const active=scenarioData.filter(x=>state.scenario[x[0]]).map(x=>x[2]);let score=parseInt($('#labScore').textContent);state.experiments.unshift({career:careers[state.selectedCareer].name,score,items:active.slice(0,3),time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})});state.experiments=state.experiments.slice(0,5);localStorage.setItem('eduMultiverseExperiments',JSON.stringify(state.experiments));renderExperiments();toast('Reality saved','Your alternate timeline is stored locally.');}
function renderExperiments(){const el=$('#experimentsList');if(!state.experiments.length){el.innerHTML='<div class="empty-state">No saved realities yet. Build your first one above.</div>';return;}el.innerHTML=state.experiments.map(e=>`<div class="experiment-item"><div><b>${e.career}</b><small>${e.time} • ${e.items.join(' · ')}</small></div><strong>${e.score}%</strong></div>`).join('');}
function showView(view){$$('.view').forEach(v=>v.classList.remove('active'));$(`#view-${view}`).classList.add('active');$$('.nav-item[data-view]').forEach(n=>n.classList.toggle('active',n.dataset.view===view));const names={universe:'Multiverse',careers:'Career Radar',skills:'Skill Galaxy',timeline:'Future Timeline',lab:'Multiverse Lab'};$('#pageTitle').textContent=names[view];window.scrollTo({top:0,behavior:'smooth'});}
function beep(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=540;o.type='sine';g.gain.value=.025;o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.07);}catch(e){}}
function init(){renderCareerCards('#careerPreview',4);renderCareerCards('#careerFull');renderTree();renderSkills();renderTimeline();renderScenarios();renderExperiments();
 $$('.nav-item[data-view]').forEach(n=>n.onclick=()=>{showView(n.dataset.view);$('#sidebar').classList.remove('open');});$$('[data-view-target]').forEach(b=>b.onclick=()=>showView(b.dataset.viewTarget));$$('.node').forEach(n=>n.onclick=()=>openCareer(n.dataset.career));
 $('#exploreBtn').onclick=()=>{document.querySelector('#view-universe .section-head').scrollIntoView({behavior:'smooth'});toast('Universe opened','Choose a career planet to inspect its future.');};$('#simulateBtn').onclick=()=>updateSimulation(true);$('#saveScenario').onclick=saveScenario;$('#modalClose').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.remove('open')};$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#themeBtn').onclick=()=>{document.body.classList.toggle('light');toast('Visual mode','Theme controls are ready for customization.');};$('#soundBtn').onclick=()=>{state.sound=!state.sound;$('#soundBtn').textContent=state.sound?'🔊':'🔇';toast('Sound '+(state.sound?'enabled':'muted'),'Simulation feedback sound toggled.');};$('#expandTree').onclick=()=>{$('#treeDetail').textContent='All three primary branches are available. Click any branch to explore its next decision.';toast('Tree expanded','Three primary realities are ready to explore.');};$('#refreshRadar').onclick=()=>{Object.values(careers).forEach(c=>c.score=Math.max(65,Math.min(97,c.score+Math.round(Math.random()*6-3))));renderCareerCards('#careerFull');toast('Radar recalculated','Your simulated career signals have been refreshed.');};$('#addSkillBtn').onclick=()=>{skills[4][1]=Math.min(100,skills[4][1]+8);renderSkills();toast('Skill completed','Machine Learning progress increased by 8%.');};$('#timelineAlt').onclick=()=>{timeline[2][1]='Alternate project';timeline[2][2]='You chose a different project universe. New possibilities are opening.';renderTimeline();toast('Alternate reality created','Timeline branch updated.');};$('#resetBtn').onclick=()=>{if(confirm('Reset your Education Multiverse simulation?')){localStorage.removeItem('eduMultiverseExperiments');location.reload();}};
 document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();showView('lab');}});
}
init();
